version: '3'

services:
  mercure:
    image: dunglas/mercure
    restart: unless-stopped
    ports:
      - "32768:80"
    environment:
      SERVER_NAME: ':80'
      CORS_ALLOW_ORIGIN: 'http://127.0.0.1:8000'
      MERCURE_PUBLISHER_JWT_KEY: '!ChangeThisMercureHubJWTSecretKey!'
      MERCURE_SUBSCRIBER_JWT_KEY: '!ChangeThisMercureHubJWTSecretKey!'
    # Comment the following line to disable the development mode
    command: /usr/bin/caddy run --config /etc/caddy/Caddyfile.dev
    volumes:
      - ./docker/Caddyfile:/etc/caddy/Caddyfile.dev

volumes:
  ###> symfony/mercure-bundle ###
  mercure_data:
  mercure_config:
###< symfony/mercure-bundle ###
